// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-8tkNdbacOADqYpmS_KKlv82jBsqFa94',
    appId: '1:685473647071:web:762326cebae34499a01c6a',
    messagingSenderId: '685473647071',
    projectId: 'codigotrauma-39bbe',
    authDomain: 'codigotrauma-39bbe.firebaseapp.com',
    storageBucket: 'codigotrauma-39bbe.appspot.com',
    measurementId: 'G-3DR0F56Q8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ3M-pMtvoMSpBN1ENFs41GJjPrjgI-Tk',
    appId: '1:685473647071:android:5fb309c3e20ea339a01c6a',
    messagingSenderId: '685473647071',
    projectId: 'codigotrauma-39bbe',
    storageBucket: 'codigotrauma-39bbe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZuQpJFWWBgA1a5YJetfyRzaYKsne_nTE',
    appId: '1:685473647071:ios:ce40dd8e0aed649aa01c6a',
    messagingSenderId: '685473647071',
    projectId: 'codigotrauma-39bbe',
    storageBucket: 'codigotrauma-39bbe.appspot.com',
    iosBundleId: 'com.example.emergenciasApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZuQpJFWWBgA1a5YJetfyRzaYKsne_nTE',
    appId: '1:685473647071:ios:ce40dd8e0aed649aa01c6a',
    messagingSenderId: '685473647071',
    projectId: 'codigotrauma-39bbe',
    storageBucket: 'codigotrauma-39bbe.appspot.com',
    iosBundleId: 'com.example.emergenciasApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-8tkNdbacOADqYpmS_KKlv82jBsqFa94',
    appId: '1:685473647071:web:45d331fd18568d92a01c6a',
    messagingSenderId: '685473647071',
    projectId: 'codigotrauma-39bbe',
    authDomain: 'codigotrauma-39bbe.firebaseapp.com',
    storageBucket: 'codigotrauma-39bbe.appspot.com',
    measurementId: 'G-ZSKLNFPG44',
  );

}